### ISSUE TITLE
 Need to store Processes created by `connect` as instance variables if it is used within a ProcessModel of a Hierarchical Process.

### ISSUE THREAD

**Issue by gkarray** [lava-nc/lava-dnf#20]
**Objective of issue:**
State that currently, we cannot simply make use of `lava-dnf`'s `connect` method to connect child Neural Processes of a Hierarchical Process without storing the `Dense` + 2 `Reshape` Processes as instance variables.

**Background:**
`lava-dnf`'s `connect` method is supposed to be a high-lever helper method the user uses to create connections between two Neural Processes with connectivity matrix (synaptic weights) derived from a list of Operation objects given as argument.

Roughly, it does the following things :
- Compute weights (connectivity matrix)
- Create `Dense` Process

It **returns the created `Dense` Process**. The user chooses whether to use it (store it) or not.

That being said ;
Neural Processes currently available in the `proc` library (`LIF` Process) can by of any shape (N-D arrays).
The `Dense` Process from the `proc` library represent weights as 2-D arrays, which, implicitly, means the Neural Processes connected at both ends have to be 1-D arrays.
Ultimately, `ReshapePort` should be added either :
- On the `OutPort` of Neural Processes to "virtually" reshape output with arbitrary shape to 1-D **(N-D arrays to 1-D arrays)**, or 
- On the `InPort` and `OutPort` of the `Dense` Process to "virtually" reshape input with arbitrary shape to 1-D **(N-D arrays to  1-D arrays)** and "virtually" reshape output with 1-D shape to arbitrary shape **(1-D arrays to M-D arrays)**.

As stated in #7, `connect` currently implement reshaping with dedicated Reshape Processes, i.e it additionally creates 2 Reshape Processes for each Dense Process created.

**Lava version:**
- [x] **0.2.0**

**Lava-dnf version:**
- [x] **0.1.0**

**I'm submitting a ...** 

- [x] bug report

**Current behavior:**

I want to create a Hierarchical Process (with ProcessModel inheriting from `AbstractSubProcessModel`).
Inside its `__init__` definition, I want to connect connect child Neural Processes with the `connect` method.

Code snippet 1 contains the definition of an example of what I want to build.

Code snippet 2 contains the definition of a `SourceProcess` (created for testing purposes) that always sends an array full of ones.

When `SourceProcess` is connected to `DNF`, and the whole is run as is done in Code snippet 3, the ones sent from `SourceProcess` never reach the input_conn of `DNF`.

However ;
- If the `connect` is tweaked so as to also return the created `Reshape` Processes, and
- If the `DNFProcessModel` is tweaked so as to store the `Reshape` Processes as instance variables

Ones reach the `Dense` Process.

I suspect this has something to do with the way the `Builder` creates instances of `AbstractSubProcessModel` and their child Process at compile time.
I think when the overall network is compiled, if an instance of `AbstractSubProcessModel` defines child process, it has to store them as instance variables, otherwise they are discarded from compilation.

Namely, I suspect that is what happens for `Reshape` Processes created in the `connect` method in our case.
If the `Reshape` Process at the input side of the `Dense` Process created by `connect` doesn't get compiled, the data sent by `SourceProcess` never reaches the `Dense` Process.

**Related code:**

**Code snippet 1 :**

```python

class DNF(AbstractProcess):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        shape = validate_shape(kwargs.pop("shape"))

        self.u = Var(shape=shape, init=np.zeros(shape))

        self.s_in = InPort(shape=shape)

        self.s_out = OutPort(shape=shape)



@implements(proc=DNF, protocol=LoihiProtocol)
class DNFProcessModel(AbstractSubProcessModel):
    def __init__(self, proc):
        shape = proc.init_args.get("shape")

        self.population = LIF(shape=shape, du=409, dv=2047, vth=200)

        self.input_conn = connect(proc.in_ports.s_in, self.population.a_in, [Weights(25)])
        kernel = MultiPeakKernel(amp_exc=83, width_exc=3.75, amp_inh=-70, width_inh=7.5)
        self.recurrent_conn = connect(self.population.s_out, self.population.a_in, [Convolution(kernel)])

        self.population.s_out.connect(proc.out_ports.s_out)

        proc.vars.u.alias(self.population.vars.u)

```

**Code snippet 2 :**

```python

class SourceProcess(AbstractProcess):
    """
    Process that sends arbitrary vectors

    Parameters
    ----------
    shape: tuple, shape of the process
    """

    def __init__(self,
                 **kwargs: ty.Union[ty.Tuple, np.ndarray]) -> None:
        super().__init__(**kwargs)
        shape = kwargs.get("shape")
        data = kwargs.get("data")

        self.data = Var(shape=shape, init=data)
        self.a_out = OutPort(shape=shape)


@implements(proc=SourceProcess, protocol=LoihiProtocol)
@requires(CPU)
@tag("bit_accurate_loihi")
class SourceProcessBoolModel(PyLoihiProcessModel):
    data: np.ndarray = LavaPyType(np.ndarray, bool)
    a_out: PyOutPort = LavaPyType(PyOutPort.VEC_DENSE, bool)

    def run_spk(self) -> None:
        """Send data every timestep"""
        self.a_out.send(self.data)

```

**Code snippet 3 :**

```python

def main():
    shape = (20, )

    run_cfg = Loihi1SimCfg(select_tag="bit_accurate_loihi",
                           select_sub_proc_model=True)
    condition = RunSteps(num_steps=10)

    source = SourceProcess(shape=shape, data=np.ones(shape, dtype=bool))
    dnf = DNF(shape=shape)

    source.a_out.connect(dnf.s_in)

    dnf.run(condition=condition, run_cfg=run_cfg)

    dnf.stop()


if __name__ == '__main__':
    main()

```

**Comment by gkarray** [comment]
``I think my suspicions were correct :

- In the `_map_proc_to_model` method of the `Compiler` class (in `compiler.py`), which corresponds to one of the "steps" of compilation, there is the following lines of code : 

```python

if issubclass(model_cls, AbstractSubProcessModel):
      # Recursively substitute SubProcModel by sub processes
      sub_map = self._expand_sub_proc_model(model_cls, p, run_cfg)
      proc_map.update(sub_map)

```

I think these lines take care of searching for nested child Processes of a Hierarchical Process to add them to the list of Processes to be compiled.

- Later in the  `_expand_sub_proc_model` method, there is the following lines : 

```python

sub_procs = model.find_sub_procs()
proc.register_sub_procs(sub_procs)

```

These lines execute the `find_sub_procs` method of the instance of `AbstractSubProcessModel` to find the `sub_procs` and register them.

- As expected, the `find_sub_procs` of `AbstractSubProcessModel` goes through the list of `attr` of the object and return those that are of type Processes. 
 
```python

    def find_sub_procs(self) -> ty.Dict[str, AbstractProcess]:
        """Finds and returns all sub processes of ProcessModel."""
        procs = OrderedDict()
        for attr_name in dir(self):
            attr = getattr(self, attr_name)
            if isinstance(attr, AbstractProcess):
                procs[attr_name] = attr
        return procs

```

This means that if a child Process to a Hierarchical Process is not stored as an instance variable (as an `attr`), it will not be returned by the `find_sub_procs` method and consequently would not be registered for compilation by the compiler.

**Comment by mathisrichter** [comment]
@gkarray Could you please review this, check whether it is still an issue, and turn it into a user story?

**Comment by gkarray** [comment]
Closing this issue as it seems that it was solved after changing the use of the `Reshape` Processes to `ReshapePorts`.
