### ISSUE TITLE
About the support of the new lava package

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dnf#25]
Hello ,
It seems this library requires the previous lava version 0.2.0. If I remove the requirement about the release version, would this library still work correctly?

**Comment by mathisrichter** [comment]
Hi @ahmetakman 
I apologize for this ridiculously long delay in responding to your issue. I will keep an eye on the Github issues of lava-dnf from now on.

When an algorithm library like lava-dnf depends on a particular version of lava, users should be using that particular version of lava with it. It may be that newer versions of lava also work but this has not been tested and may break.

In this particular case, there were breaking changes in the newest lava versionthat prevented lava-dnf to depend on the newest version without more work on lava-dnf.
